const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.Text,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Behaviors.Bullet,
		C3.Behaviors.Flash,
		C3.Plugins.Audio,
		C3.Plugins.Button,
		C3.Plugins.Arr,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Browser.Acts.Close,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.TiledBg.Cnds.CompareWidth,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Exps.max
	];
};
self.C3_JsPropNameTable = [
	{Sprite: 0},
	{BT_playgame: 0},
	{BT_gi: 0},
	{BG_gi: 0},
	{BT_home: 0},
	{Touch: 0},
	{Browser: 0},
	{BG_menu: 0},
	{BT_BK: 0},
	{GM_MOD: 0},
	{BT_A: 0},
	{BT_B: 0},
	{BT_C: 0},
	{BT_D: 0},
	{BT_EX: 0},
	{BG_A: 0},
	{T_SC: 0},
	{T_Question: 0},
	{T_TM: 0},
	{ChoiceIndex: 0},
	{T_Choice: 0},
	{TB_heart: 0},
	{T_Check: 0},
	{T_D: 0},
	{BG_COLO: 0},
	{BG_G: 0},
	{BT_G: 0},
	{BG_EX: 0},
	{BG_GOV: 0},
	{BT_RA: 0},
	{BT_MENU: 0},
	{BT_Stop: 0},
	{BT_GOV: 0},
	{Solid: 0},
	{floor_A: 0},
	{Bullet: 0},
	{mon1: 0},
	{Flash: 0},
	{man1: 0},
	{Spark: 0},
	{BG_GOV2: 0},
	{BG_B: 0},
	{mon2: 0},
	{BG_C: 0},
	{floor_C: 0},
	{mon3: 0},
	{BG_D: 0},
	{floor_D: 0},
	{mon4: 0},
	{BT_EX2: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Audio: 0},
	{Button: 0},
	{Ar_Choice: 0},
	{AnswerB: 0},
	{AnswerC: 0},
	{AnswerD: 0},
	{AnswerA: 0},
	{Result: 0},
	{Answer: 0},
	{Score: 0},
	{Timer: 0},
	{Operator: 0},
	{Num1: 0},
	{Num2: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	BT_playgame: class extends self.ISpriteInstance {},
	BT_gi: class extends self.ISpriteInstance {},
	BG_gi: class extends self.ISpriteInstance {},
	BT_home: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	BG_menu: class extends self.ISpriteInstance {},
	BT_BK: class extends self.ISpriteInstance {},
	GM_MOD: class extends self.ISpriteInstance {},
	BT_A: class extends self.ISpriteInstance {},
	BT_B: class extends self.ISpriteInstance {},
	BT_C: class extends self.ISpriteInstance {},
	BT_D: class extends self.ISpriteInstance {},
	BT_EX: class extends self.ISpriteInstance {},
	BG_A: class extends self.ISpriteInstance {},
	T_SC: class extends self.ITextInstance {},
	T_Question: class extends self.ITextInstance {},
	T_TM: class extends self.ITextInstance {},
	T_Choice: class extends self.ITextInstance {},
	TB_heart: class extends self.ITiledBackgroundInstance {},
	T_Check: class extends self.ITextInstance {},
	T_D: class extends self.ITextInstance {},
	BG_COLO: class extends self.ITiledBackgroundInstance {},
	BG_G: class extends self.ISpriteInstance {},
	BT_G: class extends self.ISpriteInstance {},
	BG_EX: class extends self.ISpriteInstance {},
	BG_GOV: class extends self.ISpriteInstance {},
	BT_RA: class extends self.ISpriteInstance {},
	BT_MENU: class extends self.ISpriteInstance {},
	BT_Stop: class extends self.ISpriteInstance {},
	BT_GOV: class extends self.ISpriteInstance {},
	floor_A: class extends self.ISpriteInstance {},
	mon1: class extends self.ISpriteInstance {},
	man1: class extends self.ISpriteInstance {},
	Spark: class extends self.ISpriteInstance {},
	BG_GOV2: class extends self.ITiledBackgroundInstance {},
	BG_B: class extends self.ISpriteInstance {},
	mon2: class extends self.ISpriteInstance {},
	BG_C: class extends self.ISpriteInstance {},
	floor_C: class extends self.ISpriteInstance {},
	mon3: class extends self.ISpriteInstance {},
	BG_D: class extends self.ISpriteInstance {},
	floor_D: class extends self.ISpriteInstance {},
	mon4: class extends self.ISpriteInstance {},
	BT_EX2: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Button: class extends self.IButtonInstance {},
	Ar_Choice: class extends self.IArrayInstance {},
	AnswerB: class extends self.ITextInstance {},
	AnswerC: class extends self.ITextInstance {},
	AnswerD: class extends self.ITextInstance {},
	AnswerA: class extends self.ITextInstance {}
}